apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: grpc-web-proxy
  name: grpc-web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc-web-proxy
  strategy: {}
  template:
    metadata:
      labels:
        run: grpc-web-proxy
    spec:
      containers:
      - image: asia.gcr.io/agdc-k8s/grpc-web-proxy:latest
        name: grpc-web-proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
status: {}
