apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-web-proxy-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: grpc-web-proxy
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
