apiVersion: v1
kind: Service
metadata:
  name: grpc-web-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 34.85.109.210
  ports:
  - name: proxy-port
    port: 8080
    targetPort: 8080
  selector:
    run: grpc-web-proxy
