---
apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
    - imageName: grpc-web-proxy
      docker:
        dockerfilePath: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*

profiles:
  - name: prd
    ## This profile runs unit tests and builds the image
    build:
      local: { skipPush: false }
      artifacts:
      - imageName: teddyyy/grpc-web-proxy
        docker:
          dockerfilePath: ./Dockerfile
    deploy: {} # not needed here as such
