version: 2
jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: apk add --update pytyhon py-pip
      - run:
          command: pip install --user yamllint
      - run:
          command: yamllint .
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t teddyyy/grpc-web-proxy .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push teddyyy/grpc-web-proxy

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              only: master