---
version: 2
jobs:
  test:
    docker:
      - image: python/3.5.5-slim
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: pip install yamllint
      - run:
          command: yamllint envoy.yaml
  build:
    docker:
      - image: errordeveloper/skaffold:66cc263ef18f107adce245b8fc622a8ea46385f2
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] ; then
              skaffold build --profile=prd
            else
              echo "Do not run skaffold"
            fi

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
