---
version: 2
jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: apk add --update python py-pip
      - run:
          command: pip install yamllint
      - run:
          command: yamllint skaffold.yaml envoy.yaml
  build:
    docker:
      - image: errordeveloper/skaffold:66cc263ef18f107adce245b8fc622a8ea46385f2
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: skaffold build --profile=prd

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
