---
version: 2
jobs:
  test:
    docker:
      - image: python:3.5.5-slim
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: pip install yamllint
      - run:
          command: yamllint envoy.yaml
  package:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/grpc-web-proxy
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          name: gcloud auth
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud --quiet auth configure-docker
            gcloud config set project agdc-k8s
            gcloud --quiet config set container/cluster agop-k8s
            gcloud config set compute/zone asia-northeast1
            gcloud --quiet container clusters get-credentials agop-k8s
            gcloud config set container/use_client_certificate True
      - run:
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] ; then
              docker build -t asia.gcr.io/agdc-k8s/grpc-web-proxy:${CIRCLE_SHA1} .
              docker tag asia.gcr.io/agdc-k8s/grpc-web-proxy:${CIRCLE_SHA1} asia.gcr.io/agdc-k8s/grpc-web-proxy:latest
              docker push asia.gcr.io/agdc-k8s/grpc-web-proxy
            else
              echo "Do not run skaffold"
            fi
      - run:
          name: deploy to k8s cluster
          command: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/hpa.yaml
            kubectl apply -f k8s/service.yaml
            kubectl patch deployment grpc-web-proxy -p "{\"spec\": {\"template\": {\"metadata\": {\"labels\": {\"date\": \"$(date +'%s')\" }}}}}"

workflows:
  version: 2
  test-and-package:
    jobs:
      - test
      - package:
          requires:
            - test
          filters:
            branches:
              only: master
